### ISSUE TITLE
The app crashed when I tried to add hentai as favorite after exiting the hentai for a few times

### ISSUE THREAD

**Issue by sagorahmed** [ttdyce/NHentaiViewer#8] opened 2019-07-29 07:07 UTC
**Describe the bug**
When I tried to add hentai as the favorite after exiting the hentai for a few times, then the app crashed.

**To Reproduce**
1. Open the app.
2. Open a hentai and press back to exit from it.
3. Now press "add as your favorite" button to add it as your favorite.
4. Notice the bug. (If you haven't seen the bug yet then try those steps for a few times to different hentai).

**Expected behavior**
I Expected that I could add a hentai as the favorite after exiting from it for a few times.

**Screenshots**
![fff](https://media.giphy.com/media/QZIeOFFukm2jaeJL1g/giphy.gif)

**Smartphone (please complete the following information):**
 - Device: Samsung A5
 - OS: Android 6.0.1
 - Version 1.1.0

**LogCat**
```
07-29 12:44:52.222 29897 29897 E AndroidRuntime: FATAL EXCEPTION: main

07-29 12:44:52.222 29897 29897 E AndroidRuntime: Process: personal.ttd.nhviewer, PID: 29897

07-29 12:44:52.222 29897 29897 E AndroidRuntime: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:323)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:132)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at com.bumptech.glide.Glide.with(Glide.java:723)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at personal.ttd.nhviewer.glide.GlideApp.with(GlideApp.java:104)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at personal.ttd.nhviewer.Controller.InnerPageActivity.initRecycleView(InnerPageActivity.java:140)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at personal.ttd.nhviewer.Controller.InnerPageActivity.lambda$initComicShowing$0$InnerPageActivity(InnerPageActivity.java:131)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at personal.ttd.nhviewer.Controller.-$$Lambda$InnerPageActivity$qmnv4vEcn_ntgmzyIPkgI5PVGCA.onResponse(lambda)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at personal.ttd.nhviewer.Model.api.NHTranlator$Companion$getComicById$documentRequest$2.onResponse(NHTranlator.kt:224)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at personal.ttd.nhviewer.Model.api.NHTranlator$Companion$getComicById$documentRequest$2.onResponse(NHTranlator.kt:215)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:78)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:106)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

07-29 12:44:52.222 29897 29897 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by ttdyce** [comment] 2019-07-30 11:40
It is a bit difficult to reproduce, It may take some time for me to debug

**Comment by ttdyce** [comment] 2019-08-03 06:06
The issue should be fixed in the next release. 
Thanks for the report. 

---

### For developers
The exception is caused by placing a context variable in an async task (a callback method in my case). 
It is solved by separating the async task and the context variable. 

Reference: 
https://github.com/bumptech/glide/issues/1126

> Alternatively use the hacky workaround of **caching Glide.with(context) into a variable earlier**, so when you receive the byte[] data from the background into the UI you don't need to do with -> no exception.

**Closed by ttdyce** 2019-08-03 06:06 UTC
Labels: bug

**Comment by ttdyce** [comment] 2019-08-03 07:38
I will upload the APK later today!
